# Generated by Django 4.2.7 on 2023-11-24 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False, unique=True)),
                ('name', models.TextField()),
                ('password', models.CharField(max_length=65)),
                ('api_token', models.CharField(max_length=65)),
                ('verified', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('cur_code', models.CharField(max_length=65)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False, unique=True)),
                ('name', models.TextField()),
                ('password', models.CharField(max_length=65)),
                ('api_token', models.CharField(max_length=65)),
                ('verified', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('cur_code', models.CharField(max_length=65)),
            ],
        ),
    ]
